development_:
  adapter: postgres
  database: core

__development:
  adapter: sqlite
  database: dev.db

test:
  adapter: sqlite
  database: test.db

development:
  adapter: 'jdbc'
  encoding: utf8
  charset: utf8
  url: 'mysql://localhost/development?user=root&password=root'

test__:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: test_lims_api
  username: root
  password:
  socket: /tmp/mysql.sock
